import type { PersonaId } from '../domain/types/persona';
import {
  PERSONA_REGISTRY,
  type PersonaDisclaimerTier,
} from '../personas/persona.registry';

const TIER_COPY: Record<
  PersonaDisclaimerTier,
  (fullName: string, persona: PersonaId) => string
> = {
  cohort: (fullName) =>
    `AI simulation of ${fullName} — ChaiCode cohort-authorized educational demo. Not the real person.`,
  contemporary: (fullName) =>
    `You are chatting with an AI parody of ${fullName}. This is NOT the real ${fullName}. Content is generated by an LLM from publicly available material. Nothing said here is financial advice, endorsement, or a factual statement by the real individual.`,
  'deceased-recent': (fullName, persona) => {
    if (persona === 'jobs') {
      return 'AI parody of Steve Jobs (1955-2011), drawing from his publicly available speeches and writings. Not endorsed by Apple or the Steve Jobs estate. Educational fair-use only.';
    }
    return `AI parody of ${fullName}, drawing from publicly available speeches and writings. Educational fair-use only. Not endorsed by the individual's estate.`;
  },
  historical: (fullName) =>
    `AI parody of ${fullName} drawing from publicly available writings. Educational research. Content should not be taken as historically authoritative statements.`,
};

/** In-chat banner copy keyed by registry `disclaimerTier` (V2 Phase 5). */
export const personaChatDisclaimer = (persona: PersonaId): string => {
  const { disclaimerTier, fullDisplayName } = PERSONA_REGISTRY[persona];
  return TIER_COPY[disclaimerTier](fullDisplayName, persona);
};
